# Configuration file for re-command
# This file contains default values for local development
# In Docker, this file is generated by entrypoint.sh from environment variables

# Navidrome Configuration
ROOT_ND = ""
USER_ND = ""
PASSWORD_ND = ""
MUSIC_LIBRARY_PATH = "/path/to/music"
TEMP_DOWNLOAD_FOLDER = "/path/to/temp"

# ListenBrainz API Configuration
LISTENBRAINZ_ENABLED = False
ROOT_LB = "https://api.listenbrainz.org"
TOKEN_LB = ""
USER_LB = ""

# Last.fm API Configuration
LASTFM_ENABLED = False
LASTFM_API_KEY = ""
LASTFM_API_SECRET = ""
LASTFM_USERNAME = ""
LASTFM_PASSWORD = ""
LASTFM_PASSWORD_HASH = ""
LASTFM_SESSION_KEY = ""

# LLM Suggestions Settings
LLM_ENABLED = False
LLM_PROVIDER = ""
LLM_API_KEY = ""
LLM_MODEL_NAME = ""
LLM_BASE_URL = ""

# Deezer Configuration
DEEZER_ARL = ""

# Download Method
DOWNLOAD_METHOD = "streamrip"

# Album Recommendation Settings
ALBUM_RECOMMENDATION_ENABLED = os.getenv('ALBUM_RECOMMENDATION_ENABLED', 'false').lower() == 'true'

# UI Visibility Settings
HIDE_DOWNLOAD_FROM_LINK = os.getenv('HIDE_DOWNLOAD_FROM_LINK', 'false').lower() == 'true'
HIDE_FRESH_RELEASES = os.getenv('HIDE_FRESH_RELEASES', 'false').lower() == 'true'

# Comment Tags for Playlist Creation
TARGET_COMMENT = "lb_recommendation"
LASTFM_TARGET_COMMENT = "lastfm_recommendation"
ALBUM_RECOMMENDATION_COMMENT = "album_recommendation"
LLM_TARGET_COMMENT = 'llm_recommendation'

# History Tracking
PLAYLIST_HISTORY_FILE = "playlist_history.txt"

# Caching for fresh releases (in seconds)
FRESH_RELEASES_CACHE_DURATION = 300

# Deezer API Rate Limiting
DEEZER_MAX_CONCURRENT_REQUESTS = 3
